export const products = [
  {
    id: 1,
    name: "Gamer Gear Pro Controller",
    description: "High-performance gaming controller",
    price: 59.99,
    inStock: 100,
    category: "electronics",
  },
  {
    id: 2,
    name: "Luminous VR Headset",
    description: "Immersive virtual reality experience",
    price: 199.99,
    inStock: 50,
    category: "electronics",
  },
  {
    id: 3,
    name: "TechTonic Energy Drink",
    description: "Refreshing energy boost",
    price: 2.99,
    inStock: 1000,
    category: "beverages",
  },
  {
    id: 4,
    name: "Laser Lemonade Machine",
    description: "Futuristic lemonade maker",
    price: 499.99,
    inStock: 25,
    category: "electronics",
  },
  {
    id: 5,
    name: "Hypernova Headphones",
    description: "High-fidelity audio experience",
    price: 129.99,
    inStock: 75,
    category: "electronics",
  },
  {
    id: 6,
    name: "AeroGlow Desk Lamp",
    description: "Sleek and energy-efficient lighting",
    price: 39.99,
    inStock: 200,
    category: "electronics",
  },
  {
    id: 7,
    name: "Zest Juicers",
    description: "Healthy juice extraction",
    price: 79.99,
    inStock: 100,
    category: "electronics",
  },
  {
    id: 8,
    name: "Flexi Wearables",
    description: "Comfortable and stylish fitness trackers",
    price: 49.99,
    inStock: 150,
    category: "electronics",
  },
  {
    id: 9,
    name: "Glimmer Lamps",
    description: "Ambient lighting for any space",
    price: 99.99,
    inStock: 75,
    category: "electronics",
  },
  {
    id: 10,
    name: "Aqua Filters",
    description: "Advanced water filtration system",
    price: 129.99,
    inStock: 50,
    category: "electronics",
  },
];
